### ISSUE TITLE
Autocomplete and Lost Focus (onBlur)

### ISSUE THREAD

**Issue by fmclopes** [xoxco/jQuery-Tags-Input#102]
Hello,

When I set property autocomplete_url and put some text and lose focus the tag is not added.
Without property autocomplete_url works correctly.

My code:
 $('#tags_3').tagsInput({
                width: '99%',
                height: '23px',
                autocomplete_url: 'TagHandler.json', 
                defaultText: 'Add one tag',
                minChars: 3
            });

Thanks

**Comment by jdelatorre312** [comment]
Anyway you could add the code you used to fix this issue?

**Comment by wguzgg** [comment]
I can't see the change merged into main branch, can anyone fix this issue? Now I have to directly edit the codes as below, line 277:
                    } else if (jQuery.ui.autocomplete !== undefined) {
                                                var disable = false;
                                                autocomplete_options["open"] = function(event, ui) {
                                                    disable = true;
                                                }
                                                autocomplete_options["close"] = function(event, ui) {
                                                    disable = false;
                                                    $(this).focus();
                                                }
                        $(data.fake_input).autocomplete(autocomplete_options).blur(function(event) {
                                                    if (!disable) {
                                                        var val = $(data.fake_input).val();
                                                        if( (val.length > 0 && data.minChars <= val.length) && (!data.maxChars || (data.maxChars >= val.length))) {
                                                            $(data.real_input).addTag(val, {focus: true,unique: (settings.unique)});
                                                            $(data.fake_input).resetAutosize(settings);
                                                        }
                                                    }
                                                });

**Comment by IchigoWalker** [comment]
```
$(data.fake_input).focusout(data, function(event) {
                        if( (event.data.minChars <= $(event.data.fake_input).val().length) && (!event.data.maxChars || (event.data.maxChars >= $(event.data.fake_input).val().length)) )
                            $(event.data.real_input).addTag($(event.data.fake_input).val(),{focus:true,unique:(settings.unique)});
                        $(event.data.fake_input).resetAutosize(settings);
                });
```

This code will help. Add it after `$(data.fake_input).bind('keypress',data,function(event) {` block
