### ISSUE TITLE
Please specify which jQuery.Autocomplete plugin it is.

### ISSUE THREAD

**Issue by felixding** [xoxco/jQuery-Tags-Input#149]
There are many Autocomplete plugins. To name a few:
- http://www.pengoworks.com/workshop/jquery/autocomplete.htm
- https://github.com/dyve/jquery-autocomplete
- http://jqueryui.com/autocomplete/

All lot these are somehow called jQuery Autocomplete. In the readme, it would be better if it's clearly stated which one of them works with jQuery Tags Input.

**Comment by vkostromin** [comment]
http://xoxco.com/x/tagsinput/jquery-autocomplete/jquery.autocomplete.min.js and http://xoxco.com/x/tagsinput/jquery-autocomplete/jquery.autocomplete.css return 404 now... Please check
