### ISSUE TITLE
Problem with multi taginputs on one page.

### ISSUE THREAD

**Issue by danishahmed150** [xoxco/jQuery-Tags-Input#184]
Hi,
I creating a php page with xoxco jQuery-Tags-Input 5 inputs fields on one page just two are working fine but the problems start with 3 also no JS or any other errors show on page. Also input fields just get one value on post.
Please any one help with the above issue.
Thanks,
Dani.

**Comment by lucknerjb** [comment]
If you're still having an issue with this, can you provide a jsfiddle? thanks
