### ISSUE TITLE
Assign tagInput in dynamicly apened element

### ISSUE THREAD

**Issue by potasiyam** [xoxco/jQuery-Tags-Input#186]
After a jquery append if I want to assign tagInput again to newly apended fields, it seems tagInput reassigns to old hidden fields also. So it creates multiple tag input fields for previous ones. For example check this fiddle
http://jsfiddle.net/aRBkV/

What to do in this situation?

**Comment by lucknerjb** [comment]
Are you still seeing this issue? From your jsfiddle, the only way I could get it to duplicate the field was to have something like this:

```
$(function() {
    $('.tags').tagsInput();
    $('.add').click(function(){
        $('.wrap').append('<input type="text" class="tags"></input>');
        $('.tags').tagsInput();
    });
});
```

I'm not quite sure what you were trying to show in your fiddle though

**Comment by potasiyam** [comment]
This is exactly what I was talking about. http://jsfiddle.net/aRBkV/3/
I have put your suggestion in that fiddle. Now check the fiddle and try to put some tag in first field, then click add field.

**Comment by potasiyam** [comment]
For more clarification, if you call tagsInput() second time for a specific element, it will add a new tag field. http://jsfiddle.net/aRBkV/4/
It basically binds the already rendered fields and doubles the tag fields.

**Comment by lucknerjb** [comment]
Ah ok, I see what you mean now. I managed to fix the issue with the following code:

```
$(function() {
    $('.tags').tagsInput();
    $('.tags').attr('data-tagsinput-init', true);
    
    $('.add').click(function(){
        $('.wrap').append('<input type="text" class="tags"></input>');
        $('.tags').not('[data-tagsinput-init]').tagsInput();
    });
});
```

This is by no means a proper solution since you would have to add the data attribute to the new tags input but it shows what works.

I'll change the plugin init function to add this data attribute and when you call $().tagsinput() again, it will only initialize inputs that do not have this attribute

**Comment by potasiyam** [comment]
Sounds great.  Or you can introduce some parameter to re-render fields with something like tagsInput("refresh");
Thanks for the fix.

**Comment by lucknerjb** [comment]
Nice idea! I'll add this to the V2 list of methods that can be called. For now though, I'll add the data-attribute
