### ISSUE TITLE
Bug in tagExist function

### ISSUE THREAD

**Issue by viktor-poltorak** [xoxco/jQuery-Tags-Input#196]
Function tagExist in minimized version have bug
Normal version:
$.fn.tagExist = function(val) {
		var id = $(this).attr('id');
		var tagslist = $(this).val().split(delimiter[id]);
		return (jQuery.inArray(val, tagslist) >= 0); //true when tag exists, false when not
	};

Minimized variant:
 a.fn.tagExist=function(b)
    {return jQuery.inArray(b,a(this))>=0};

a(this) not equals $(this).val().split(delimiter[id])
function doesn't works

**Comment by LouTerrailloune** [comment]
Duplicate of #208

**Comment by omarismail** [comment]
Thats weird. @viktor-poltorak I dont have that function inside mine.
