### ISSUE TITLE
defaultText value can't be larger

### ISSUE THREAD

**Issue by vinothkumarma** [xoxco/jQuery-Tags-Input#200]
Hi, Thanks for your great plugin,

Could you please tell me how to add larger text on defaultText, because if I add it wont display fully in the textbox.

For example, If I give "Add Tags" it works perfectly, but if I give "Please Add tag separated by comma" as a defaultText, then only few words are displaying others not displaying. Kindly suggest me how to solve this issue.

**Comment by lucknerjb** [comment]
@shanpratheep, @vinothkumarma  the proper way of doing this is to set the following in the init object:

minInputWidth: '225px', You can then customize the width for responsiveness, etc...
