### ISSUE TITLE
Can't remove 'x' from tag without breaking tag functionality

### ISSUE THREAD

**Issue by gregmatthewcrossley** [xoxco/jQuery-Tags-Input#201]
I'm trying to replace the 'x' character at the end of each tag with a fontawesome "close" character (just for stylistic reasons). 

I know I can do this by editing the plugin code itself, but I'm trying to do this after the tag is loaded using jQuery. I tried selecting the <a> element and using the .empty() method to clear the 'x' away, but this seems to break the plugin all together. 

Can anyone help me with this?

**Comment by lucknerjb** [comment]
see #247
