### ISSUE TITLE
Save model in backbone after remove tag

### ISSUE THREAD

**Issue by makromat** [xoxco/jQuery-Tags-Input#205]
Hello guys,

Thank you for amazing piece of code, I would like to use it in my app but I have one issue. I don't know how to call backbone save function after click to remove link (inside tag). I have tried add event click to this <a> element but it doesnt work. This event is working only if I remove this:

    return $('#' + id).removeTag(escape(value));

Thanks for any ideas!
Best regards,
Makromat

**Comment by lucknerjb** [comment]
Have a look at the "onRemoveTag" callback function
