### ISSUE TITLE
Avoid onChange on initialization

### ISSUE THREAD

**Issue by dtemes** [xoxco/jQuery-Tags-Input#210]
I would like to see a way to avoid the onChange callback being call on initialization, we are using an ajax callback to post the tags list to the server in order to save it, so it is being saved on initialization with the same value it is being initialisez.

**Comment by lucknerjb** [comment]
Yeah that makes sense. We're working on cranking out some improvements with a new version and the events system is being changed a little. Until then, are you able to use a flag to differentiate between init and non-init onChange runs?
