### ISSUE TITLE
Maintaining project

### ISSUE THREAD

**Issue by lucknerjb** [xoxco/jQuery-Tags-Input#211]
Hey XOXCO,

I noticed that no one has committed to this project since 2013. Would there be any interest in transferring the repository over or be added as a collaborator? I would love to take care of some of the open issues and continue to add features to the plugin.

Best!

**Comment by omarismail** [comment]
@benbrown @esoelzer what do you guys think of @lucknerjb 's proposal? I like this project and would like to see these issues resolved. 

Thanks!

**Comment by martincarlin87** [comment]
I think this project could do with an active maintainer as  I have to modify the plugin every time I use it because I use it for a CC list for emails and the changes I make would be much better added as options supplied when initialised.

What I have done for 1.3.3 are:

add a function to validate email addresses:

    $.fn.checkEmail = function(str) {
        var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
        return emailPattern.test(str);
  }


Changed the `x` from the removal to a font-awesome icon

    $('<span>').addClass('tag').append(
       $('<span>').text(value).append('&nbsp;&nbsp;'),
           $('<a>', {
               href  : '#',
               title : 'Removing tag',
              html  : '<i class="fa fa-remove"></i>'
           }).click(function () {
               return $('#' + id).removeTag(escape(value));
          })
      ).insertBefore('#' + id + '_addTag');

Add more keys to the delimiter:

    if (event.which==event.data.delimiter.charCodeAt(0) || event.which == 13 || event.which == 32 || event.which == 186 || event.which == 59) {

so the email addresses are delimited with a space, return and semi-colon.

This might be better as a regex.

Finally, I then check the tag value is a valid email address

    if (value !='' && skipTag != true && $.fn.checkEmail(value)) { 

These would all need to only apply when an email option is present but I thought I'd quickly share anyway.

**Comment by lucknerjb** [comment]
hey @martincarlin87, I like some of the ideas that you propose, however, they would have to be done as options, especially the email pattern. God knows email and url validation are one thing developers will never reach a consensus on.

**Comment by lucknerjb** [comment]
@omarismail, glad to see you're on board mate.

**Comment by benbrown** [comment]
@lucknerjb Hey! We'd love to have more contributors, or even a new maintainer!

I am currently on vacation, but when I get back next week, let's do it!

**Comment by benbrown** [comment]
@lucknerjb Hey! I'm back!

I would happily add you as a contributor to this project. I will email you!

**Comment by lucknerjb** [comment]
Hey Ben!

Thanks for the heads up! I replied to a message last night from Tim. Maybe
coordinate with him?

Either way, I'm glad to work on this with you guys and potentially others!

Cheers,
Luckner Jr

**Comment by benbrown** [comment]
Who is Tim? Someone on Github?

On Tue, Feb 17, 2015 at 10:55 AM, Luckner Jr. Jean-Baptiste <
notifications@github.com> wrote:

> Hey Ben!
>
> Thanks for the heads up! I replied to a message last night from Tim. Maybe
> coordinate with him?
>
> Either way, I'm glad to work on this with you guys and potentially others!
>
> Cheers,
> Luckner Jr
> On Feb 17, 2015 11:52 AM, "Ben Brown" <notifications@github.com> wrote:
>
> > @lucknerjb <https://github.com/lucknerjb> Hey! I'm back!
> >
> > I would happily add you as a contributor to this project. I will email
> you!
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/xoxco/jQuery-Tags-Input/issues/211#issuecomment-74702682
> >
>
> > .
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/xoxco/jQuery-Tags-Input/issues/211#issuecomment-74703347>
> .
>



-- 
Ben Brown
/* I am a software designer and online community pioneer.
Learn more about what I do at http://XOXCO.com & http://PEOPLEPODS.net
and learn more about me at http://BENBROWN.com. */

**Comment by benbrown** [comment]
@lucknerjb is in! Updates to come!
