### ISSUE TITLE
Tags like 12356-0001, version 1.3.3

### ISSUE THREAD

**Issue by orrbo** [xoxco/jQuery-Tags-Input#218]
Im trying to highlite tags with a hyphen but get the  error:
Invalid regular expression: /\b(['15001-0020','test'])\b/: Range out of order in character class 

Using this code: 
var tags = $("#passingTags").val();
var tags_array = new Array(tags);

$('#tags_2').tagsInput({
		width: 'auto',
		onChange: function(elem, elem_tags)
		{
			  $('.tag', elem_tags).each(function()
			  {
				if($(this).text().search(new RegExp('\\b(' + tags_array.join('|') + ')\\b')) >= 0)	
				  $(this).css('background-color', 'yellow');
			  });
			}
		});

I guess the regexp interprets - as a range and not as a part of the tag, is there someway to escape the hyphen?

**Comment by lucknerjb** [comment]
Seems like the problem is with your regex. Try using this instead:

```
var regex = new RegExp('(' + tags_array.join('|') + ')');
```

Noticed how the \b has been removed from the regex string. You don't need to explicitly have your regex search anywhere since it will by default - you didn't put in any delimiter tags like $ or ^.
