### ISSUE TITLE
Jquery 1.11.1 Issue with delimiter.

### ISSUE THREAD

**Issue by jazo10** [xoxco/jQuery-Tags-Input#219]
I was getting an issue with Jquery 1.11.1  

Uncaught TypeError: Cannot use 'in' operator to search for '0' in , jquery.min.js:2 
r      jquery.min.js:2 
m.extend.each  jquery.tags.js:367
 _checkDelimiter   jquery.tags.js:294 
(anonymous function)     jquery.min.js:3
m.event.dispatch       jquery.min.js:3
 r.handle

Issue was caused by jquery looking for an array, where a string was provided.

This was modified in the last update 
https://github.com/xoxco/jQuery-Tags-Input/commit/7a050e1940c5ae02a7e252803c77d40e4e5bb483

The fix is to change the default value back to an array(line 186)

```javascript
delimiter: [','],
```

edit: formatting

**Comment by lucknerjb** [comment]
@jazo10 - Thanks for noticing the issue. We're working on getting unit tests setup to catch these kinds of issues. In the meantime, I'll fix this up tonight and push the fix!
