### ISSUE TITLE
reset tags then import new ones

### ISSUE THREAD

**Issue by simo163** [xoxco/jQuery-Tags-Input#222]
Basically I want to remove all tags and import new one but it actually maintains the old tags. I do something like:

```javascript
$('#tags').importTags('');
$('#tags').importTags('foo, bar, all');
```
Any idea how could I reset and import and same time?

**Comment by lucknerjb** [comment]
There is no way to remote AND import new tags at the same time at the moment. It would be a good addition to have though. We'll get it implemented in v2.

**Comment by simo163** [comment]
@lucknerjb I saw some of your comments in bootstrap-tagsinput, maybe you would know if this is possible with bootstrap-tagsinput?? It seems like I have the same result.

**Comment by lucknerjb** [comment]
@simo163 I was wrong in my last comment - I had just joined the project at the time. When you call importTags('some_tag'), the plugin will automatically remove the existing tags and replace them with the new ones that you import.

If you are still having issues, can you explain what happens? Maybe there's a small disconnect in what you're saying and what I understood :-)
