### ISSUE TITLE
Uncaught TypeError:

### ISSUE THREAD

**Issue by oxcarga** [xoxco/jQuery-Tags-Input#223]
Does anyone else has had this issue as well?
http://screencast.com/t/huAVNqmqgq

**Uncaught TypeError: Cannot use 'in' operator to search for '0' in ,**

Seems to be happening here:

    var _checkDelimiter = function(event){
        var flag = false;// defalut no match

        if(event.which == 13){// Enter
            flag = true;
        }

        $.each(event.data.delimiter ,function(index, value){
            if(event.which == value.charCodeAt(0)){
                flag = true;
            }
        });

        return flag;
    }

#Edit
Just tested passing the 'delimiter' and worked, like this:

    $('#tags').tagsInput({
        'delimiter': [',',';']
    });

**Comment by MichalZalecki** [comment]
Awesome, thanks!

**Comment by jeteon** [comment]
I ran into something similar and that fixed it for me too. Seems like something's wrong with either the code or the documentation if that option is not optional.

**Comment by lucknerjb** [comment]
Hey guys, I know a bug was introduced in April so that may be why this happened. The current version in master should be fine though. All tests (currently in the testing branch) are passing.
