### ISSUE TITLE
Use properties from the input being replaced

### ISSUE THREAD

**Issue by wiscoDude** [xoxco/jQuery-Tags-Input#226]
I might be completely off target here, but it was a surprise to me that this code didn't utilize properties such as placeholder, width, height, etc of the input being replaced.  Just a thought.

**Comment by lucknerjb** [comment]
The majority of tag plugins behave the same way - replacing the element and providing a way for you to style it the way the other element was.

It might be possible to have an option that allows you to grab certain properties from the existing element but I think this is more of a one-off request.
