### ISSUE TITLE
main in bower.js is incorrect

### ISSUE THREAD

**Issue by wridgers** [xoxco/jQuery-Tags-Input#228]
https://github.com/xoxco/jQuery-Tags-Input/blob/70486a440f1941184560ed941deb870ab670b9bc/bower.json#L4

I think this should be

```
"main": ["src/jquery.tagsinput.js", "src/jquery.tagsinput.css"]
```

**Comment by luke-oneill** [comment]
Seconded. I just ran into this problem also.
