### ISSUE TITLE
tags gets appended with time when using it with angular 

### ISSUE THREAD

**Issue by khyamay** [xoxco/jQuery-Tags-Input#230]
I am trying to use this plugin with angular but having few issues. I have created a directive to use it, but when changing the view, id on the input seems to be append with time like "tags1431552377968_tagsinput". Is there a reason for this  and how can I avoid it??

**Comment by khyamay** [comment]
oh well this seems to do that trick 
var id = $(this).attr('id');
$('#'+id+'_tag');

**Comment by veerendra456** [comment]
hi,
same issue i am getting .i am giving id(technology) for input field.
but when added code like:
$('#technology').tagsInput({ .... }); 
it giving like: tags1462968029982_tag
so validation not working in this scenario.

**Comment by khyamay** [comment]
yeah it adds the time to for each tags input, u can access it by

```
var id = $(this).attr('id');
$('#'+id+'_tag');
```

coz it will hide #technology, so u can use the above method to make your validation work

**Comment by veerendra456** [comment]
i  am getting that issue when used with jquery...
