### ISSUE TITLE
Slightly long default text gets trimmed

### ISSUE THREAD

**Issue by Qrysto** [xoxco/jQuery-Tags-Input#258]
When defaultText is a bit longer than default, it's not fully displayed: http://jsfiddle.net/7aDak/6710/

**Comment by lucknerjb** [comment]
Seems like the width param is not kicking in properly. I won't be able to get to this until later today or tomorrow but if you have a PR ready, please submit :-)

**Comment by lucknerjb** [comment]
There is an option that is not very well documented that you can use. When you instantiate the plugin, pass in the "minInputWidth" option with the size that you want the input to have to accommodate the placeholder text length
