### ISSUE TITLE
how to get and set as objects?

### ISSUE THREAD

**Issue by basith374** [xoxco/jQuery-Tags-Input#319]
i've the following array:

```
[
    {'id':1,'name':'John'},
    {'id':2,'name':'Drew'},
    {'id':3,'name':'Alex'},
];
```

i need to get the names as suggestions and store them as objects in the input field so that i can later retrieve them by id. how can i do this?

**Comment by speedygfw** [comment]
Names are unique. So you don't should use objects in combination with tags-input.

**Comment by basith374** [comment]
but the names are fetched from a database. they may not be unique. besides, i only need their id's to post the data to the server.

**Comment by speedygfw** [comment]
wrong behavior. you should really use tags as they are. (in this definition)
a comma seperated list of strings

**Comment by speedygfw** [comment]
you can try to map your list with ids on clienside (even here by name ;) )

something like: (after submit, before send to server)

```
var tags = mytagelement.getTags();
for (x in yourobjlist)
{
     if (tags.indexOf(yourobjlist[x].name)....
    .....
    .....
}
```

**Comment by basith374** [comment]
ok thanks for the advice
