### ISSUE TITLE
Something is broken

### ISSUE THREAD

**Issue by Co0olCat** [xoxco/jQuery-Tags-Input#321]
Hi,

Great product. We are fans and love it.

In local environment everything works as expected.

In production - issues (started about beginning of July 2016).

You can see it in your jsfiddle: http://jsfiddle.net/7aDak/

Please advise.

Thank you.

Kind regards,
TY

**Comment by gregmurray** [comment]
any luck on getting this to work?

**Comment by Co0olCat** [comment]
I wish to wrong - but it looks like this ship is unmanned.

Thank you.

You produced great product.

**Comment by Co0olCat** [comment]
Ok. While solving issue another issue I have noticed that code of plugin was minified. It turned out I have enabled in CloudFlare minify JS -> this was creating issues (formating and so on) -> After I have disabled Cloudflare feature -> it now works as expected.

Appologies. You did great product. This was my mistake.

Thank you.

Kind regards,
TY
