### ISSUE TITLE
get value of removed tag ?

### ISSUE THREAD

**Issue by navotera** [xoxco/jQuery-Tags-Input#337]
how to get value of removed tag ?

**Comment by Omarmaste** [comment]
i same faced issue, please fix this issues

**Comment by stefanKBL** [comment]
hi, late but...

`$("input[class^='some-tags']").each(function () { 
    $(this).tagsInput({ 
    	'width': '100%',
    	onRemoveTag: function(elm) { // term is elm
    		console.log(elm);
    	},
  });
});`

**Comment by navotera** [comment]
Thanks bro
