### ISSUE TITLE
"autocomplete_url" can also be an object?

### ISSUE THREAD

**Issue by memoryprojector** [xoxco/jQuery-Tags-Input#68]
When using tagsInput with the jQuery.ui.autocomplete widget, the autocomplete_url can be a reference to an array, an array of object, a url, or a function.

Calling it "autocomplete_url" is misleading since it does not have to be a url and I almost discounted using this solution. It's trivial, but I have changed it to "autocomplete_src" in my work.

Otherwise awesome work!

**Comment by iamandiradu** [comment]
@appel`s example works perfectly :D.
