### ISSUE TITLE
Unescaped forward slash in regex

### ISSUE THREAD

**Issue by glen-84** [xoxco/jQuery-Tags-Input#71]
``` if(event.keyCode == 8 || String.fromCharCode(event.which).match(/\w+|[áéíóúÁÉÍÓÚñÑ,/]+/)) { ```

should be:

``` if(event.keyCode == 8 || String.fromCharCode(event.which).match(/\w+|[áéíóúÁÉÍÓÚñÑ,\/]+/)) { ```

**Comment by glen-84** [comment]
It seems that this is not a bug. I think it was an issue with the syntax highlighting in the editor that I was using.

**Comment by lucknerjb** [comment]
Thanks for the update @glen-84. Sorry I closed the issue without getting back to you. I only did it due to how long it had been since you created it.

**Comment by glen-84** [comment]
No worries. :smile:
